name: CI - Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: princemitnick/fast-api-ci-cd:latest

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Start FastAPI server
        run: |
          pip install fastapi uvicorn
          uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          sleep 10

      - name: RUN OSWAP ZAP baseline scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://localhost:8000/health'
          format: json

      - name: Upload ZAP HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.html